export const gameMenuContent = {
  meta: {
    title: 'Game Menu',
  },
  sections: {
    currentGames: 'Your Games',
    loadingGames: 'Loading games',
  },
  gameRow: {
    statusYourTurn: 'YOUR TURN',
    statusWaiting: 'WAITING',
    opponentActive: 'vs. Opponent',
    opponentWaiting: 'Waiting for opponent',
    elementBadgeLabel: 'Element:',
    actionPlay: 'Play',
    actionOpen: 'Open',
  },
  emptyState: {
    heading: 'No games yet',
    body: 'Start a new game or join one with a friend.',
    ctaNew: 'New Game',
    ctaJoin: 'Join Game',
  },
  bottomNav: {
    newGame: 'New Game',
    setManager: 'Set Manager',
  },
  newGameModal: {
    heading: 'New Game',
    opponentLabel: 'Opponent',
    opponentPlaceholder: 'Player tag or friend name',
    elementLabel: 'Your Element',
    submit: 'Start Game',
    cancel: 'Cancel',
    errorNoOpponent: 'Enter an opponent player tag.',
    errorNoElement: 'Choose an element to continue.',
    errorCreateFailed: 'Couldn\'t create the game. Please try again.',
  },
  joinGameModal: {
    heading: 'Join Game',
    gameIdLabel: 'Game ID',
    gameIdPlaceholder: 'Paste the game ID from your friend',
    elementLabel: 'Your Element',
    submit: 'Join Game',
    cancel: 'Cancel',
    errorNoGameId: 'Enter a game ID to continue.',
    errorNoElement: 'Choose an element to continue.',
    errorJoinFailed: 'Couldn\'t join that game. Check the ID and try again.',
  },
} as const
