export const styleGuideContent = {
  meta: {
    title: 'Style Guide',
    subtitle: 'Design system reference for WeatherForm',
  },
  sections: {
    brand:      'Brand',
    colours:    'Colour System',
    typography: 'Typography',
    spacing:    'Spacing',
    components: 'Components',
    elements:   'Elements',
  },
  colour: {
    groups: {
      backgrounds: 'Backgrounds',
      text:        'Text',
      accent:      'Brand Accent',
      elements:    'Element Palettes',
      feedback:    'Feedback',
    },
    swatches: {
      ink:         { label: 'Ink',           token: '$wf-ink',          hex: '#080F0C', use: 'Deepest surface — navbar, splash, footers' },
      base:        { label: 'Base',          token: '$wf-base',         hex: '#0F1A1E', use: 'Default app background' },
      raised:      { label: 'Raised',        token: '$wf-raised',       hex: '#17272D', use: 'Cards, panels, modals' },
      panel:       { label: 'Panel',         token: '$wf-panel',        hex: '#1F3540', use: 'Secondary panels, input backgrounds' },
      border:      { label: 'Border',        token: '$wf-border',       hex: '#2B4858', use: 'Dividers, strokes, separators' },
      textPri:     { label: 'Text Primary',  token: '$wf-text-pri',     hex: '#EEF2F0', use: 'Headings, labels, primary body' },
      textSec:     { label: 'Text Secondary',token: '$wf-text-sec',     hex: '#A3BDC0', use: 'Supporting text, metadata' },
      textMuted:   { label: 'Text Muted',    token: '$wf-text-muted',   hex: '#587C80', use: 'Placeholders, disabled states' },
      accentDark:  { label: 'Accent Dark',   token: '$wf-accent-dark',  hex: '#C4911A', use: 'Pressed / active states' },
      accent:      { label: 'Accent',        token: '$wf-accent',       hex: '#F7B731', use: 'Primary buttons, logo, active indicators' },
      accentHover: { label: 'Accent Hover',  token: '$wf-accent-hover', hex: '#FFCF5C', use: 'Hover states' },
      danger:      { label: 'Danger',        token: '$wf-danger',       hex: '#E05A5A', use: 'Errors, destructive actions' },
    },
    elements: {
      tide: {
        label:   'Tide',
        flavour: 'Ocean blue — overwhelms',
        base:   { label: 'Base',   token: '$wf-tide-base',   hex: '#0077B6' },
        accent: { label: 'Accent', token: '$wf-tide-accent', hex: '#00B4D8' },
        bg:     { label: 'Bg',     token: '$wf-tide-bg',     hex: '#0D3D6B' },
      },
      gale: {
        label:   'Gale',
        flavour: 'Ice silver — scours',
        base:   { label: 'Base',   token: '$wf-gale-base',   hex: '#CBD5E1' },
        accent: { label: 'Accent', token: '$wf-gale-accent', hex: '#F1F5F9' },
        bg:     { label: 'Bg',     token: '$wf-gale-bg',     hex: '#2A3A4A' },
      },
      dune: {
        label:   'Dune',
        flavour: 'Deep terracotta — absorbs',
        base:   { label: 'Base',   token: '$wf-dune-base',   hex: '#A84510' },
        accent: { label: 'Accent', token: '$wf-dune-accent', hex: '#D96728' },
        bg:     { label: 'Bg',     token: '$wf-dune-bg',     hex: '#3D1A0A' },
      },
    },
  },
  typography: {
    intro: 'Cinzel for brand and structural text. DM Sans for all UI and body copy.',
    specimens: {
      logo:        { label: 'wf-type-logo',        meta: 'Cinzel 900 · 40px · 5px tracking' },
      display:     { label: 'wf-type-display',     meta: 'Cinzel 700 · 24px · 3px tracking' },
      heading:     { label: 'wf-type-heading',     meta: 'Cinzel 600 · 14px · 2px tracking' },
      eyebrow:     { label: 'wf-type-eyebrow',     meta: 'Cinzel 600 · 12px · 2.5px tracking' },
      eyebrowCard: { label: 'wf-type-eyebrow--card', meta: 'Cinzel 600 · 8px · 2px tracking' },
      bodyLg:      { label: 'wf-type-body-lg',     meta: 'DM Sans 400 · 14px · 1.65 leading' },
      body:        { label: 'wf-type-body',        meta: 'DM Sans 400 · 14px · 1.6 leading' },
      label:       { label: 'wf-type-label',       meta: 'DM Sans 700 · 12px · 0.3px tracking' },
      caption:     { label: 'wf-type-caption',     meta: 'DM Sans 500 · 12px' },
    },
    sampleText:      'The quick brown fox jumps over the lazy dog',
    sampleTextBrand: 'Tide · Gale · Dune',
  },
  spacing: {
    intro: 'All spacing is derived from a 4px base unit.',
    tokens: {
      xs:   { token: '$space-xs',   value: '4px' },
      sm:   { token: '$space-sm',   value: '8px' },
      base: { token: '$space',      value: '16px' },
      md:   { token: '$space-md',   value: '20px' },
      lg:   { token: '$space-lg',   value: '32px' },
      xl:   { token: '$space-xl',   value: '48px' },
      xxl:  { token: '$space-xxl',  value: '64px' },
      xxxl: { token: '$space-xxxl', value: '80px' },
    },
  },
  components: {
    buttons: {
      label:     'Buttons',
      primary:   'Primary',
      secondary: 'Secondary',
      ghost:     'Ghost',
      danger:    'Danger',
      disabled:  'Disabled',
    },
    inputs: {
      label:       'Form Inputs',
      textLabel:   'Text input',
      placeholder: 'Enter a value…',
      selectLabel: 'Select',
      selectOpt:   'Choose an option',
    },
    cards: {
      label:    'Cards',
      eyebrow:  'Card context',
      heading:  'Card Heading',
      bodyText: 'Card body text sits on a raised surface. Use for lists, match rows, and content panels.',
    },
  },
} as const
